### PR TITLE
Add umd suffix to umd bundle

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by renatorib** [comment]
Why the suffix?
I always see a pattern in libs like `<name>.js` and `<name>.min.js`.

**Comment by TrySound** [comment]
I'm gonna propose bundles for cjs and esm, so this distinction will be helpful.
```
.cjs.js
.esm.js
.min.js
.umd.js
```

**Comment by TrySound** [comment]
By the way, what is the purpose of `.min.js`? I'm not sure anybody will create production app with react from minified umd files.

**Comment by renatorib** [comment]
@TrySound About minified version: I think it costs nothing (it's just a extra config), and there may be people who need it.

**Pull request merged**
