### PR TITLE
Combine UMD configs into rollup multiconfig and add size snapshot

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by renatorib** [comment]
How it work?

**Comment by TrySound** [comment]
Rollup accepts array of configs. I'm gonna add cjs and esm bundles instead of babeled files.

**Comment by TrySound** [comment]
Added [rollup-plugin-size-snapshot](https://github.com/TrySound/rollup-plugin-size-snapshot). I created this plugin for improving bundles of frontend projects.

**Comment by renatorib** [comment]
Got it!

**Pull request merged**
