### PR TITLE
Fix flow types

### PR DESCRIPTION
**Pull request by TrySound**
Would be good to release this fixes

### CODE REVIEW

**Comment by renatorib** [comment]
Great! Could you type the `compose` function too? It's the only one missing I think

**Comment by TrySound** [comment]
@renatorib I already said it's not typable. I can only make it any.

**Comment by renatorib** [comment]
Well, I guess it's better than nothing. :sweat_smile:
At least we can ensure that people are using the function correctly.

**Comment by TrySound** [comment]
@renatorib There is a problem. render or children are not optional. We can't omit them when create component.

**Comment by renatorib** [comment]
Humm. Got it.
It's possible to do it with overloads?

**Comment by TrySound** [comment]
What do you mean?

**Comment by renatorib** [comment]
It's just a question. I don't know how overloading works. It's possible to solve this problem with overloads?

**Comment by renatorib** [comment]
Anyway. I'll merge this. I'll see what I can do with the compose in another PR. What do you think?

**Comment by TrySound** [comment]
We already use overload for each component. The first one works with children and the second one with render props.

**Comment by renatorib** [comment]
So we can't do this with compose too?

**Comment by TrySound** [comment]
The problem is not compose itself. The problem is components which can't be created without one prop and passed to compose. So nothing can be used with compose.

**Comment by renatorib** [comment]
Oh. Got it. Sorry.
So render and children are optional, it's not?

**Comment by TrySound** [comment]
Compose require them to be optional. But it's not type safe with regular use. So currently components require one of children or render to be passed.

**Comment by TrySound** [comment]
Can we release this and maybe discuss `compose` later? It always can be released as feature.

**Comment by renatorib** [comment]
Alright

**Comment by TrySound** [comment]
Friendly ping :)

**Comment by TrySound** [comment]
Would be good if you will let me publish such fixes.

**Comment by renatorib** [comment]
@TrySound published `v1.0.0-alpha.3`

**Pull request merged**
