### PR TITLE
Add composeEvents initial work

### PR DESCRIPTION
**Pull request by renatorib**
Ref #32 

TODO
- [x] Implement
- [x] Tests
- [ ] Docs & readme
- [x] Flow types

### CODE REVIEW

**Comment by renatorib** [comment]
I think it's okay to merge this way, but it still needs a doc and reference in readme

**Comment by renatorib** [comment]
I think this is hard to type, isn't it?
@TrySound

**Comment by TrySound** [comment]
Yep. Since this feature covers native events mostly, which do not have definitions, we can be less specific with
```js
declare export function composeEvents(...Array<{ [name: string]: Function }>): Function
```

**Comment by souporserious** [comment]
Sorry I never got around to this 😓. I've been swamped in other projects. This looks great! Excited to be able to use it.

**Comment by renatorib** [comment]
Thanks @TrySound! I was thinking it would be something like that.

**Comment by renatorib** [comment]
@souporserious no worries! xD 
The code was already ready there in issue

**Comment by renatorib** [comment]
I'm sorry for not finish this PR yet. I'll try to spend some time here this week.

**Pull request merged**
