### PR TITLE
Refac onChange event arg of State Containers

### LINKED ISSUE #70: Refactor components' `onChange` to match same `initial` type
I find it very inconsistent that you pass `initial={boolean}` to `<Toggle>` and onChange fires with `{on: boolean}`.
I think onChange should call with the fundamental component's state

Toggle -> boolean (on)
Counter -> number (count)
Value -> any (value)
List -> array (list)
Hover -> boolean (isHovered)

Example:
```jsx
<Counter onChange={count => console.log(count)}>
 {/* ... */}
</Counter>
```

etc...

### PR DESCRIPTION
**Pull request by renatorib**
Closes #70

### CODE REVIEW

**Comment by renatorib** [comment]
I thought of 3 ways to do this:

1. **State mainStateKey**
The first way was to couple to the <State> a key (something like `mainStateKey="on"`) reference to tell which state prop will be fired. So I would get this key, get the value of the state and send it onChange.

2. **onChange wrapper** 
The second way would be to create a wrapper for onChange acting in the middle of `originalOnChange` coming from user's input to `onChange` that is passed to <State>

3. **State value** 
The third way would be for me to refactor <State> so that the primary value of all states was `value`. In this case I would be able to set a non-object value to the initial of <State>, like `<State initial={true}>`. So it was just firing `state.value` on onChange.
```diff
-state = {
-  ...this.props.initial,
-}
+state = {
+  value: this.props.initial
+}
```

---

I think the 3rd option is the best approach. However, it would take a lot of changes in the implementation that would break, mainly, the current behavior of State's setState. Using raw state, React merges setState in state object. Using state.value this behavior would not be the same (of course we could solve this problem by applying the same behavior in `_setState`, but I do not think we need it now)

I chose the 2nd because it was simple to apply and could do individually, as is already done with other behaviors, such as `renderProps`,` set`, among others.

I tried to avoid the 1st because I think that it accouples a non-sense behavior to the State itself. Imagine typing State's onChange. I think it's weird.

**Comment by renatorib** [comment]
Yes, we should add Form tests. However, it is not being affected in this PR. I think we can do this in another PR (there are other components without tests as well)

**Comment by renatorib** [comment]
We need to update the flow types indeed. I forgot that :(

**Comment by TrySound** [comment]
Okay, I will add tests and update flow types

**Comment by renatorib** [comment]
I think I can make changes to the flow types

**Comment by renatorib** [comment]
Here are. I think it's done.

**Comment by TrySound** [comment]
Let me add Form test before merge

**Pull request merged**
