### PR TITLE
1.0 initial works

### PR DESCRIPTION
**Pull request by renatorib**
TODO:

### State
  - [x] Implemented
  - [x] Docs
  - [x] Types
  - [x] Tests

### Toggle
  - [ ] Implemented
  - [ ] Docs
  - [ ] Types
  - [ ] Tests

### Counter
  - [ ] Implemented
  - [ ] Docs
  - [ ] Types
  - [ ] Tests

### List
  - [ ] Implemented
  - [ ] Docs
  - [ ] Types
  - [ ] Tests

### Map
  - [ ] Implemented
  - [ ] Docs
  - [ ] Types
  - [ ] Tests

### Set
  - [ ] Implemented
  - [ ] Docs
  - [ ] Types
  - [ ] Tests

### Value
  - [ ] Implemented
  - [ ] Docs
  - [ ] Types
  - [ ] Tests

### Compose
  - [ ] Docs
  - [ ] Implemented
  - [ ] Types
  - [ ] Tests

---

### Input
  - [ ] Implemented
  - [ ] Docs
  - [ ] Types
  - [ ] Tests

### Form
  - [ ] Docs
  - [ ] Implemented
  - [ ] Types
  - [ ] Tests

--- 

### Focus
  - [ ] Docs
  - [ ] Implemented
  - [ ] Types
  - [ ] Tests

### Hover
  - [ ] Docs
  - [ ] Implemented
  - [ ] Types
  - [ ] Tests

### Active
  - [ ] Docs
  - [ ] Implemented
  - [ ] Types
  - [ ] Tests

---

### Scroll
  - [ ] Docs
  - [ ] Implemented
  - [ ] Types
  - [ ] Tests

## Mouse
  - [ ] Docs
  - [ ] Implemented
  - [ ] Types
  - [ ] Tests

---

- [ ] composeEvents
- [ ] New visual identity
- [ ] Website

### CODE REVIEW

**Comment by TrySound** [comment]
You can make alpha release. Each alpha can be a breaking change, but I can try in in my projects and maybe find some cases.

**Comment by renatorib** [comment]
@TrySound I'll try to do this soon!

**Comment by TrySound** [comment]
You wanted to add ts definitions. Maybe then off checkbox with types?

**Comment by renatorib** [comment]
I've created `0.1-stable` branch to keep the 0.1 code. If needed (bugs) I'll update that branch.
Let's develop 1.0 under the `master` branch

**Comment by TrySound** [comment]
@renatorib Are you gonna to create beta release? Would be good to be able to make breaking changes after some experiments.

**Pull request merged**
