### PR TITLE
Add Mounting utility component

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by renatorib** [comment]
Older discussion about this: https://github.com/renatorib/react-powerplug/pull/41

**Comment by renatorib** [comment]
Personally I like the idea. But Idk if it fits the 'powerplug' concept of state containers. It's don't have any state.

**Comment by TrySound** [comment]
@renatorib Well, it has. :)

**Comment by TrySound** [comment]
@renatorib From mount to unmount it passes state.

**Comment by renatorib** [comment]
Not exactly. In your example you use `Value` to handle the state and not mounting itself. See, I'm not saying it's not useful, I really liked it. Like the idea of wrapping some lifecycles like that. But I do not see it fit into the lib, this does not even return a fn callback, it would not be possible to use with `compose`, for example.

**Comment by TrySound** [comment]
Okay. Let's leave it for further discussions. I'll try to fit the idea to powerplug.

**Comment by TrySound** [comment]
@renatorib I found some solution. We can extend mount/unmount callbacks with refs which are rely on them.

**Comment by TrySound** [comment]
And it's stateful. However we still need another component like `Value` or `State`, but it's like different type of state.

**Comment by renatorib** [comment]
I was thinking yesterday and I have some ideas in my head. When I mature the idea I'm going to create a discussion issue here. Meanwhile I'll leave this PR open.

**Comment by TrySound** [comment]
I don't support this idea anymore. It's better to prefer lifecycle with class. In opposite to state containers lifecycles to not introduce any functionality and may lead to many learning issues. Also 16.4 will introduce new stateful component api which will be in a way more elegant.

**Pull request closed without merging**
