### PR TITLE
Add Mounting utility component

### PR DESCRIPTION
**Pull request by TrySound**
Not sure this component fits to powerplug. We may consider it as utility. The case is composition with native DOM where it's necessary.

### CODE REVIEW

**Comment by souporserious** [comment]
I think more specific components might be nice instead of a `Mounting` component. Something like `Screen` maybe? I've been messing around with some ideas [here](https://codesandbox.io/s/r404p5w134). Trying to get some real use cases first before proposing anything 😇

**Comment by renatorib** [comment]
@TrySound sorry to close this. I'm organizing the branches... By deleting the `v1` branch it automatically closed.

**Comment by TrySound** [comment]
Just reopen it

**Comment by renatorib** [comment]
I can't reopen it Idk why
image

**Comment by renatorib** [comment]
Oh, you deleted the branch :sweat_smile:

**Comment by TrySound** [comment]
Ok

**Pull request closed without merging**
