### PR TITLE
Upgrade babel and rollup

### PR DESCRIPTION
**Pull request by TrySound**
- babel-runtime7 allows to reuse esm versions of helpers
- fixed esm output for `module` entry point. Before was cjs
- removed rollup commonjs plugin

### CODE REVIEW

**Comment by TrySound** [comment]
Also why do you export default along named exports? It's bad practice which rollup warns about.

**Comment by TrySound** [comment]
Done

**Comment by renatorib** [comment]
I will test this code maybe still today and I'm going to merge.

By the way, do you know if there is any way or if it is good practice to test the compiled code?
For example, sometimes I'm afraid to change something from the bundler / generated code and publish a broken version. How can I guarantee this integrity?

Thank you for your great contributions.

**Comment by TrySound** [comment]
It's possible to run jest with cli setup param which will mock code with built version or even a few setdifferent builds.

**Comment by alexkrolick** [comment]
Afaik the --cli flag just prevents Jest from creating missing snapshots, nothing about prod mode (that is controlled by env vars).

**Comment by TrySound** [comment]
@alexkrolick I mean param in cli, not --cli param.
http://facebook.github.io/jest/docs/en/cli.html#config-path

**Comment by alexkrolick** [comment]
Right, and that was a typo anyways.

To test the build output, probably the main thing is to write a few tests that 1) build first 2) import from `dist` instead of `src`

**Pull request merged**
