### PR TITLE
0.4.0

### PR DESCRIPTION
**Pull request by renatorib**
This version adds some of new components of 1.0 without any breaking change.

**Adds**
- [x] Hover (like css hover)
- [x] Focus (like css focus)
- [x] Active (like css active)
- [x] Index
- [x] Value
- [x] Loading
- [x] Form

- [x] Possibility to use render prop instead of children

- [x] New component documentations
- [x] New components in readme

### CODE REVIEW

**Comment by renatorib** [comment]
Almost done. I'm adding some tests. Not a big thing, only checking if mounts and do some operations.
I will improve test coverage in v1.0

**Comment by mathdroid** [comment]
Was about to suggest using render `props` in issues but you got it here already. 👍

**Comment by renatorib** [comment]
@mathdroid =D
I've implemented an interop function. You will can use `render` but still `children`. I did not know if it's better than pick one (inconsistency) but at least they'll be able to do the way they feel better.

I'll do a merge/release soon (I think tonight or tomorrow)

**Comment by renatorib** [comment]
Idk why I'm calling it as 0.4.0, lol

**Pull request merged**
