### PR TITLE
Add Reducer component

### PR DESCRIPTION
**Pull request by alexkrolick**
Because reducers are handy 😄 

```jsx
<Reducer
  initial={{ count: 0 }}
  actions={{
    inc: (state, amount = 1) => ({ count: state.count + amount }),
    dec: (state, amount = 1) => ({ count: state.count - amount }),
  }}
>
  {({ state, dispatch }) => (
    <div>
      Count: {state.count}
      <button onClick={() => dispatch('inc', 2)}>+</button>
      <button onClick={() => dispatch('dec', 1)}>-</button>
    </div>
  )}
</Reducer>
```

### CODE REVIEW

**Comment by renatorib** [comment]
Hey @alexkrolick, nice to see you. Thanks for you contribution! 
I totally agree with @TrySound, what you think?

**Comment by alexkrolick** [comment]
I see what you're saying, but take a look at how they handle state in Reason-React: https://reasonml.github.io/reason-react/docs/en/state-actions-reducer.html

Reducers are the built-in instead of using ad-hoc setState. I thought it would be nice to mimic that in a light-weight way and that it would fit in fairly well into Powerplug. If you don't want it I can extract it out into a separate package.

**Comment by alexkrolick** [comment]
Thanks for the feedback, I'll think more about the API

**Comment by rchubarkin** [comment]
Hi @TrySound
what do you think about it?
```jsx
import * as React from 'react'
import State from './State'
import renderProps from '../utils/renderProps'
import onChangeProp from '../utils/onChangeProp'

const StateReducer = ({ initial, reducer, onChange, ...props }) => (
  <State initial={{ state: initial }} onChange={onChangeProp(onChange, 'state')}>
    {({ state, setState }) =>
      renderProps(props, {
        state: state.state,
        dispatch: (action) => {
          setState(({ state }) => ({ state: reducer(state, action) }));
          return action;
        }
      })
    }
  </State>
)

export default StateReducer
```
reducer is simple redux reducer.
we can use any redux helpers e.g. bindActionCreators, combineReducers from redux, redux-act/actions etc.

Types:
```js
type Reducer<T, A> = (state: T, action: A) => T;

type StateReducerChange<T> = (state: T) => void

type StateReducerRenderer<T, A> = ({ state: T, dispatch: (action: A) => A }) => React.Node

type StateReducerProps<T, A> =
    | {|
      initial: T,
      reducer: Reducer<T, A>,
      onChange?: StateReducerChange<T>,
      render: StateReducerRenderer<T, A>
    |}
    | {|
      initial: T,
      reducer: Reducer<T, A>,
      onChange?: StateReducerChange<T>,
      children: StateReducerRenderer<T, A>
    |}
```
are you interested?
I don't create PR because I see a similar
thanks

**Pull request closed without merging**
