### PR TITLE
fixed Value reset error

### PR DESCRIPTION
**Pull request by harrysolovay**
I was getting the following error when trying to call `reset` on Value
screen shot 2018-10-17 at 8 32 36 am

### CODE REVIEW

**Comment by TrySound** [comment]
@harrysolovay How do you call `reset`?

**Comment by harrysolovay** [comment]
@TrySound I call it by using the `State` component & passing the resetState render-prop into onClick:

```jsx
import React from 'react'
import { State } from 'react-powerplug'
import { render } from 'react-dom'

const App = () =>
  <State initial={{ count: 0 }}>
    {({ state, setState, resetState }) => (
      <div>
        count: { state.count }
        <div>
          <button
            onClick={() => setState(({ count }) => ({
              count: count - 1,
            }))}
            children='decrement'
          />
          <button
            onClick={() => setState(({ count }) => ({
              count: count + 1,
            }))}
            children='increment'
          />
          <button
            onClick={ resetState }
            children='reset'
          />
        </div>
      </div>
    )}
  </State>

render(<App />, document.getElementById('root'));
```

**Comment by TrySound** [comment]
Well, this is the problem. reset accepts a function, but you pass `event` object. Just use arrow function there.
```
  onClick={() => resetState()}
```

**Comment by harrysolovay** [comment]
Does that matter though? My understanding is that––in many use cases––users won't want to pass a callback to reset. For the sake of more concise usage, it's beneficial to avoid error-throwing when `reset`'s argument is not a function (or specifically when it's an event)... the passing of event data into the callback doesn't need to create errors (maybe a `console.warn` instead).

Please let me know how / if the PR can be improved. I understand if you like the constraint and would rather scrap this 👍 

Just trying to help out :)

**Comment by TrySound** [comment]
Well, it's a type error. Type errors should be handled statically or runtime will be too big and slow.

**Comment by harrysolovay** [comment]
Gotcha 👍

**Comment by harrysolovay** [comment]
I just thought it would make it easier for users without type systems, who don't know why the shorter syntax isn't working. But I agree, the passing of the event data is unnecessary to begin with.

**Pull request closed without merging**
