### PR TITLE
Add RealSet component

### PR DESCRIPTION
**Pull request by TrySound**
Implementation similar to native `Set` with `add`, `clear`, `remove` and `has` methods.

### CODE REVIEW

**Comment by renatorib** [comment]
My idea is to rename current `Set` to `Map` and add this `Set` to the 1.0 version.

I think it's not a good idea to keep feeding the current version, and focus on 1.0 😅

**Comment by renatorib** [comment]
If you want, you can make a PR to 1.0 branch changing `Set` -> `Map` and creating this RealSet as `Set`, what you think?

For now I'll close this! 😄

**Comment by renatorib** [comment]
Ops, I saw that Set -> Map already done in 1.0 https://github.com/renatorib/react-powerplug/pull/25

**Comment by TrySound** [comment]
@renatorib It's just a proposal. Reopen it please. I can freely change target branch, when you will merge Set-to-Map PR.

**Comment by TrySound** [comment]
Yep. Reopen it please. I can change target branch here without new PRs.

**Comment by renatorib** [comment]
Sorry 😄

**Comment by TrySound** [comment]
Can you make me a collab? It's hard to keep branches in sync from fork.

**Comment by renatorib** [comment]
Yeah, I know it's hard. That's why I wanted to stop updating the master and focus on 1.0 only. 
Now I'm at work, I can try to help at night. 😄

**Pull request merged**
