### PR TITLE
Create `State`-like contexts

### PR DESCRIPTION
**Pull request by harrysolovay**
Hi,

Please let me know if I'm on the right track. I'm more than happy to make revisions, add typings, etc.

Kind regards,

Harry

### CODE REVIEW

**Comment by harrysolovay** [comment]
Hi

**Comment by renatorib** [comment]
Hey @harrysolovay sorry for the delay. 
I do not know if powerplug is the right guy to support this kind of functionality... I mean, I do not know if I want to put context logic and state management by context within the lib. The idea is to be a handy utility.

If you want something similar, check out this https://github.com/diegohaz/constate from @diegohaz

**Comment by renatorib** [comment]
Anyway, thank you for your efforts. I'll close by now

**Comment by harrysolovay** [comment]
@renatorib all good. Thank you for taking the time to look it through & consider the PR 👍

**Pull request closed without merging**
