### PR TITLE
Pr/mobile touch

### PR DESCRIPTION
**Pull request by farskid**
Adds support for Touch devices by adding `Touch` component.
According to https://github.com/renatorib/react-powerplug/issues/39

### CODE REVIEW

**Comment by souporserious** [comment]
This looks great! Do you think we should pass more info along like `event.touches`?

**Comment by farskid** [comment]
@souporserious We can do that too. it's probably useful to detect some pressing gestures and holdings on touch devices. I like the idea.

**Comment by renatorib** [comment]
I changed `bindTouch` to `bind`. I'll refactor all components to `bind` only (bindFocus, bindHover, etc). 
With the new compose behavior we will not have conflict problems any more.

**Comment by renatorib** [comment]
We still need to create the tests, docs and types to Touch, so I can merge this.
I'll try to help with this

**Comment by farskid** [comment]
@renatorib I'd like to help with tests and docs too. Is this fine to merge or are you guys thinking of any other APIs/Features for adding to it?

**Comment by farskid** [comment]
@souporserious @renatorib Maybe we can move the discussion about an introductory website to a new issue? It's nice to have a website with a set of demos, examples and API reference.

**Comment by renatorib** [comment]
Yes, a website is in my plans. I've started drawing it in figma, but it's just a little draft. I can create a new issue so we can all discuss about.

**Comment by TrySound** [comment]
@renatorib Let's also generate docs from `md`

**Comment by farskid** [comment]
@TrySound I agree with the idea of generating docs from `md` files automatically and even formatting them with sth like `prettier`.

**Comment by TrySound** [comment]
@farskid We already do this https://github.com/renatorib/react-powerplug/blob/master/package.json#L35

**Comment by farskid** [comment]
@TrySound Oh, never mind then :)

**Comment by renatorib** [comment]
Hey guys, let's discuss about website here https://github.com/renatorib/react-powerplug/issues/48 :

**Pull request merged**
