### PR TITLE
use onMouseDown instead of setTimeout in FocusManager

### PR DESCRIPTION
**Pull request by souporserious**
Came across some bugs recently at work with the `setTimeout` method and animations 😓, but it led me down a better path so I wanted to share it here 😇. Stoked to get rid of the hacky `setTimeout` so now everything should _just work_ as normal 🎉.

### CODE REVIEW

**Comment by TrySound** [comment]
By the way, in which browsers did you test it?

**Comment by souporserious** [comment]
Thank you! I tested all major browsers on macOS as well as mobile Safari and Chrome on iOS and even IE browsers through browserstack and all seems well!

**Comment by souporserious** [comment]
Just had a thought... do you think it would be helpful to add a prop like `blurOnEscape`? I know that this is usually a necessity for components for things like popovers, menus, etc. where this component will probably be used.

**Comment by TrySound** [comment]
I'm not sure. This will break single responsibility of this component. However achieving this using `.blur` command is tricky because we need a couple of lifecycles inside. And still I guess there will be a lifecycle component in react itself so this problem may be fixed soon. Let's just leave it without change and consider later, maybe open an issue about that.

**Comment by souporserious** [comment]
Sounds good!

**Pull request merged**
